import React from 'react';
import { FileDown } from 'lucide-react';
import { Investigation, Threat, TimelineEvent } from '../../types';
import { SeverityBadge } from '../common/SeverityBadge';
import { ScoreBadge } from '../common/ScoreBadge';

interface InvestigationReportTabProps {
  investigation: Investigation;
  threats: Threat[];
  timeline: TimelineEvent[];
  downloadingPdf: boolean;
  onDownloadPdf: () => void;
}

export const InvestigationReportTab: React.FC<InvestigationReportTabProps> = ({
  investigation,
  threats,
  timeline,
  downloadingPdf,
  onDownloadPdf,
}) => {
  const criticalThreatCount = threats.filter((t) => t.severity === 'CRITICAL').length;

  return (
    <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-8 shadow-2xl space-y-6 backdrop-blur-sm max-w-4xl mx-auto">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-6 border-b border-slate-800">
        <div>
          <span className="text-[11px] font-mono text-cyan-400 uppercase tracking-wider block">
            OFFICIAL INCIDENT REPORT PREVIEW
          </span>
          <h2 className="text-xl font-bold text-white mt-1">
            Forensic Incident Investigation Dossier
          </h2>
          <p className="text-xs text-slate-400">
            Generated by SentinelForensic Triage Engine with Apache PDFBox 3.x backend
          </p>
        </div>
        <button
          onClick={onDownloadPdf}
          disabled={downloadingPdf}
          className="px-5 py-2.5 rounded-xl bg-cyan-600 hover:bg-cyan-500 text-white text-xs font-bold flex items-center gap-2 shadow-[0_0_15px_rgba(6,182,212,0.3)] transition-all cursor-pointer disabled:opacity-50 self-start sm:self-auto"
        >
          <FileDown size={16} />
          <span>{downloadingPdf ? 'Generating PDF...' : 'Download Official PDF'}</span>
        </button>
      </div>

      <div className="space-y-6 text-xs text-slate-300 font-sans">
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 p-4 rounded-xl bg-slate-950 border border-slate-800 text-xs">
          <div>
            <span className="text-slate-500 block text-[11px]">Case Dossier ID</span>
            <span className="font-mono font-bold text-white">{investigation.investigationId}</span>
          </div>
          <div>
            <span className="text-slate-500 block text-[11px]">Lead Investigator</span>
            <span className="font-mono font-bold text-cyan-400">{investigation.investigatorName}</span>
          </div>
          <div>
            <span className="text-slate-500 block text-[11px]">Investigation Status</span>
            <span className="font-mono font-bold text-emerald-400">{investigation.status}</span>
          </div>
          <div>
            <span className="text-slate-500 block text-[11px]">Report Generation</span>
            <span className="font-mono text-slate-400">{new Date().toLocaleDateString()}</span>
          </div>
        </div>

        <div>
          <h4 className="font-bold text-sm text-white uppercase tracking-wider mb-2">
            1. Executive Summary & Incident Scope
          </h4>
          <p className="leading-relaxed bg-slate-950/40 p-4 rounded-xl border border-slate-800 text-slate-300">
            {investigation.description || 'This dossier documents forensic examination and timeline reconstruction of security events captured on target systems.'}
          </p>
        </div>

        <div>
          <h4 className="font-bold text-sm text-white uppercase tracking-wider mb-2">
            2. Forensic Telemetry Overview
          </h4>
          <div className="grid grid-cols-3 gap-4 text-center">
            <div className="p-3 rounded-xl bg-slate-950 border border-slate-800">
              <span className="text-[11px] text-slate-500 block">Total Log Events Analyzed</span>
              <span className="text-xl font-bold font-mono text-cyan-400">{timeline.length}</span>
            </div>
            <div className="p-3 rounded-xl bg-slate-950 border border-slate-800">
              <span className="text-[11px] text-slate-500 block">Correlated Threat Findings</span>
              <span className="text-xl font-bold font-mono text-red-400">{threats.length}</span>
            </div>
            <div className="p-3 rounded-xl bg-slate-950 border border-slate-800">
              <span className="text-[11px] text-slate-500 block">Critical Action Overrides</span>
              <span className="text-xl font-bold font-mono text-rose-400">{criticalThreatCount}</span>
            </div>
          </div>
        </div>

        <div>
          <h4 className="font-bold text-sm text-white uppercase tracking-wider mb-2">
            3. Detected Threats & Scoring Breakdown
          </h4>
          <div className="space-y-3">
            {threats.map((t) => (
              <div key={t.id} className="p-4 rounded-xl bg-slate-950 border border-slate-800 space-y-2">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="font-mono text-xs font-bold text-cyan-400">[{t.ruleCode}]</span>
                    <span className="font-bold text-white">{t.title}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <ScoreBadge score={t.score} />
                    <SeverityBadge severity={t.severity} size="sm" />
                  </div>
                </div>
                {t.escalationReason && (
                  <p className="text-[11px] font-mono text-red-300">
                    Escalation Reason: {t.escalationReason}
                  </p>
                )}
                <p className="text-slate-400 text-xs">{t.description}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};
